/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrangFrame;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyễn Thành lộc
 */
public class ChiTietHoaDon extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChiTietHoaDon
     */
    ArrayList<QLSP> ListSP;
    DefaultTableModel model;

    int index;

    protected String dbUsername, dbPassword;

    Connection conn;

    public ChiTietHoaDon() {
        initComponents();

         this.ListSP = new ArrayList<>();

        this.conn = this.getConnection();
        this.ListSP = this.fetchlist();
        this.RenderTable(ListSP);

    }

    protected Connection getConnection() {
         Connection conn = null;

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyBanHang";

            String dbUsername = "sa", dbPassword = "Aa123";
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ChiTietHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return conn;

    }

    protected ArrayList<QLSP> fetchlist() {
        ArrayList<QLSP> result = new ArrayList<>();

        String query = "select * from Chitiethoadon";
        try {
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                String maHDCT = rs.getString("MaHDCT");
                String maHD = rs.getString("MaHD");
                String maSP = rs.getString("MaSP");

                int soluong = rs.getInt("Soluong");

                int dongia = rs.getInt("dongia");
                int tongtien = rs.getInt("tongtien");

                result.add(new QLSP(maHDCT, maHD, maSP, soluong, dongia, tongtien));
            }

        } catch (SQLException ex) {
            Logger.getLogger(ChiTietHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return result;

    }
    public void RenderTable(ArrayList<QLSP> data) {
        model = (DefaultTableModel) this.tblChitietHD.getModel();
        model.setRowCount(0);
        for (int i = 0; i < data.size(); i++) {
            QLSP sp = data.get(i);
            model.addRow(new Object[]{
                sp.getMaHDCT(),
                sp.getMaHD(),
                sp.getMaSP(),
                sp.getSoLuong(),
                sp.getDonGia(),
                sp.getTongTien()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltendangnhap7 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChitietHD = new javax.swing.JTable();
        txtMaHD = new javax.swing.JTextField();
        txtTaikhoan3 = new javax.swing.JTextField();
        lbltendangnhap8 = new javax.swing.JLabel();
        txtThanhtien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbltendangnhap6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtmaHDCT = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txtDongia = new javax.swing.JTextField();
        lbltendangnhap9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbltendangnhap10 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnDangnhap = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbltendangnhap7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltendangnhap7.setText("Thành tiền");

        txtSoluong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Mã hóa đơn");

        txtMasp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tblChitietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HDCT", "Mã HD", "Mã SP", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblChitietHD);

        txtMaHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTaikhoan3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbltendangnhap8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltendangnhap8.setText("Tổng tiền");

        txtThanhtien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Số lượng");

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\JAVA\\JAVA3\\DuAnBanADIDAS\\Icon\\restore.png")); // NOI18N
        jButton2.setText("Sửa");

        lbltendangnhap6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltendangnhap6.setText("Mã hóa đơn chi tiết");

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\JAVA\\JAVA3\\DuAnBanADIDAS\\Icon\\close.png")); // NOI18N
        jButton3.setText("Xóa");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Mã sản phẩm");

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\JAVA\\JAVA3\\DuAnBanADIDAS\\Icon\\correct.png")); // NOI18N
        jButton4.setText("Lưu");

        txtmaHDCT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\print.png")); // NOI18N
        jButton5.setText("In ");

        txtDongia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbltendangnhap9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltendangnhap9.setText("Đơn giá");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Chi tiết hóa đơn");

        lbltendangnhap10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltendangnhap10.setText("Mã HDCT");

        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnDangnhap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDangnhap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\search (2).png")); // NOI18N
        btnDangnhap.setText("Tìm kiếm");
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltendangnhap9)
                    .addComponent(jLabel10)
                    .addComponent(lbltendangnhap6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(lbltendangnhap7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbltendangnhap8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltendangnhap10)
                                .addGap(18, 18, 18)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnDangnhap))
                            .addComponent(txtTaikhoan3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(78, 78, 78)
                                .addComponent(jButton3)
                                .addGap(74, 74, 74)
                                .addComponent(jButton4)
                                .addGap(68, 68, 68)
                                .addComponent(jButton5)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9, lbltendangnhap6, lbltendangnhap7, lbltendangnhap9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDongia, txtMaHD, txtMasp, txtSoluong, txtThanhtien, txtmaHDCT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbltendangnhap9)
                        .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtmaHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltendangnhap6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltendangnhap7))))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaikhoan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltendangnhap8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangnhap)
                    .addComponent(lbltendangnhap10))
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9, lbltendangnhap6, lbltendangnhap7, lbltendangnhap9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDongia, txtMaHD, txtMasp, txtSoluong, txtThanhtien, txtmaHDCT});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDangnhap, txtsearch});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
       
    }//GEN-LAST:event_btnDangnhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltendangnhap10;
    private javax.swing.JLabel lbltendangnhap6;
    private javax.swing.JLabel lbltendangnhap7;
    private javax.swing.JLabel lbltendangnhap8;
    private javax.swing.JLabel lbltendangnhap9;
    private javax.swing.JTable tblChitietHD;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTaikhoan3;
    private javax.swing.JTextField txtThanhtien;
    private javax.swing.JTextField txtmaHDCT;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
public void checknull() {
        try {

            //check null
            if (txtMasp.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống");
                txtMasp.requestFocus();
                return;
            }

            if (String.valueOf(txtSoluong).equals("")) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số!");
                txtSoluong.requestFocus();
                return;
            } else if (Integer.parseInt(txtSoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng > 0");
                txtSoluong.requestFocus();
                return;
            }
            if (txtDongia.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Đơn giá không được để trống!");
                txtDongia.requestFocus();
                return;
            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập thông tin!");
        }
    }

//  public void showDetail() {
//
//        QLSP sp = ListSP.get(index);
//
//        txtmaHDCT.setText(sp.maHDCT);
//        txtMasp.setText(sp.maSP);
//        txt.setText(String.valueOf(sp.getNgaynhap()));
//        txtSoluong.setText(String.valueOf(sp.soluong));
//
//        tblQLSP.setRowSelectionInterval(index, index);
//    }
}
